# ============================================
# Secret: 민감한 정보 관리
# ============================================
# 목적: DB 비밀번호, API 키 등 민감한 정보를 안전하게 저장
# 주의: 이 파일은 샘플이므로 실제 운영에서는 .gitignore에 추가하거나
#       Sealed Secrets, External Secrets 사용 권장

apiVersion: v1
kind: Secret
metadata:
  name: skk3s-secret
  namespace: default
  labels:
    app: skk3s
type: Opaque

# stringData를 사용하면 평문으로 입력 가능 (자동 base64 인코딩)
stringData:
  # 데이터베이스 접속 정보 (샘플)
  DB_HOST: "localhost"
  DB_PORT: "3306"
  DB_USERNAME: "skk3s_user"
  DB_PASSWORD: "sample_password_123"

  # Redis 접속 정보 (샘플)
  REDIS_HOST: "localhost"
  REDIS_PORT: "6379"
  REDIS_PASSWORD: "redis_password_456"

  # API 키 (샘플)
  EXTERNAL_API_KEY: "sk-1234567890abcdefghijklmnopqrstuvwxyz"
  JWT_SECRET: "your-jwt-secret-key-here-change-in-production"

# ============================================
# .env 파일로 Secret 생성하는 방법 (권장)
# ============================================
#
# 1. .env 파일 준비
#    DB_PASSWORD=real_password
#    API_KEY=real_api_key
#
# 2. kubectl 명령으로 Secret 생성
#    kubectl create secret generic skk3s-secret \
#      --from-env-file=.env
#
# 3. 확인
#    kubectl get secret skk3s-secret -o yaml
